[2023-01-06 15:03:00,739] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Demo.Dag_Test scheduled__2023-01-06T15:02:00+00:00 [queued]>
[2023-01-06 15:03:00,746] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Demo.Dag_Test scheduled__2023-01-06T15:02:00+00:00 [queued]>
[2023-01-06 15:03:00,747] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 15:03:00,747] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-06 15:03:00,748] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-06 15:03:00,762] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): Dag_Test> on 2023-01-06 15:02:00+00:00
[2023-01-06 15:03:00,767] {standard_task_runner.py:52} INFO - Started process 577 to run task
[2023-01-06 15:03:00,769] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Demo', 'Dag_Test', 'scheduled__2023-01-06T15:02:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/demonstration.py', '--cfg-path', '/tmp/tmpr55i17_b', '--error-file', '/tmp/tmp69hcf869']
[2023-01-06 15:03:00,770] {standard_task_runner.py:80} INFO - Job 34: Subtask Dag_Test
[2023-01-06 15:03:00,817] {task_command.py:369} INFO - Running <TaskInstance: Demo.Dag_Test scheduled__2023-01-06T15:02:00+00:00 [running]> on host 4bf6c36955e2
[2023-01-06 15:03:00,879] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=Dag_Test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T15:02:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T15:02:00+00:00
[2023-01-06 15:03:00,880] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-01-06 15:03:00,883] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "Hello"']
[2023-01-06 15:03:00,893] {subprocess.py:85} INFO - Output:
[2023-01-06 15:03:00,894] {subprocess.py:92} INFO - Hello
[2023-01-06 15:03:00,894] {subprocess.py:96} INFO - Command exited with return code 0
[2023-01-06 15:03:00,921] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Demo, task_id=Dag_Test, execution_date=20230106T150200, start_date=20230106T150300, end_date=20230106T150300
[2023-01-06 15:03:00,942] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-06 15:03:00,973] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
